/* GENERATED by ioc/tools/gen_db.py -- do not edit.
 * Source: ioc/tools/sg_pvs.py (spec docs/ioc/15LSS_sample_gas_IOC_spec.md \S7, \S9) */
#ifndef SGPVTABLE_H
#define SGPVTABLE_H
#include <stddef.h>

/* sgParPvs[i].suffix is the PV suffix INCLUDING the "Par:" prefix (e.g. "Par:target"). To form
   the full record name, the glue prepends only the station macro: "$(P)" + suffix, e.g.
   "$(P)" "Par:target" = "$(P)Par:target". offset is offsetof(sg_params, <field>) for the same
   field the key names (suffix "Par:target" -> field target). isInt is 1 for the five params
   whose EPICS record is longout (avgN, slopeAvgN, holdRetries, gainSchedule, lidMinSamples);
   the underlying sg_params field is still a double in every case.
   "target" is present here (offset is valid) but the glue must call sg_set_target(), not a raw
   store, so that a change while REGULATE starts settling (spec §8.12).
   "writeEnable" has NO entry: it is not a field of sg_params (it is IOC-glue state, spec §8.20). */
typedef struct { const char *suffix; size_t offset; int isInt; } sgParPv;
extern const sgParPv sgParPvs[];
extern const int sgNParPvs;

/* sgModePvs[i].suffix is BARE: just the mode-field name (e.g. "baseFlow"), with no "Mode:" and
   no slot letter. To form the full record name for slot X (one of 'A'..'D'), the glue builds
   "$(P)Mode:" + X + ":" + suffix, e.g. "$(P)Mode:B:baseFlow". offset is
   offsetof(sg_mode, <field>), to be added to a pointer to p->modes[0..3] (X - 'A'). The
   stringout "name" field is not here (it is a char[40], copied by the glue directly, not
   through this table). */
typedef struct { const char *suffix; size_t offset; } sgModePv;
extern const sgModePv sgModePvs[];
extern const int sgNModePvs;

#endif
