#!/usr/bin/env python3
"""gen_db.py: generate sampleGas.db, the two autosave .req files and sgPvTable.c/.h from the
PV table in sg_pvs.py.

Usage:
    python gen_db.py            regenerate the committed files
    python gen_db.py --check    regenerate into memory and exit 1 if any committed file differs

Deterministic: the same sg_pvs.py always produces byte-identical output, so --check can be used
as a "generated files are up to date" CI gate.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sg_pvs as T  # noqa: E402

HEADER = (
    "# GENERATED by ioc/tools/gen_db.py -- do not edit.\n"
    "# Source: ioc/tools/sg_pvs.py (spec docs/ioc/15LSS_sample_gas_IOC_spec.md \\S7, \\S9)\n"
)
CHEADER = (
    "/* GENERATED by ioc/tools/gen_db.py -- do not edit.\n"
    " * Source: ioc/tools/sg_pvs.py (spec docs/ioc/15LSS_sample_gas_IOC_spec.md \\S7, \\S9) */\n"
)

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
APP_SRC = os.path.join(REPO_ROOT, "ioc", "lssSampleGas", "lssSampleGasApp", "src")
APP_DB = os.path.join(REPO_ROOT, "ioc", "lssSampleGas", "lssSampleGasApp", "Db")

OUT_DB = os.path.join(APP_DB, "sampleGas.db")
OUT_SETTINGS_REQ = os.path.join(APP_DB, "sampleGas_settings.req")
OUT_HELIUM_REQ = os.path.join(APP_DB, "sampleGas_helium.req")
OUT_PVTABLE_H = os.path.join(APP_SRC, "sgPvTable.h")
OUT_PVTABLE_C = os.path.join(APP_SRC, "sgPvTable.c")

# ---------------------------------------------------------------------------
# small helpers
# ---------------------------------------------------------------------------

_ASCII_MAP = {
    "\u2192": "->", "\u00d7": "x", "\u2013": "-", "\u2212": "-", "\u00b1": "+/-",
    "\u0394": "d", "\u00a7": "S", "\u2019": "'",
}


def ascii_text(s):
    for k, v in _ASCII_MAP.items():
        s = s.replace(k, v)
    return s


def desc_field(s, limit=40):
    s = ascii_text(s)
    return s[:limit]


def fnum(v):
    """Deterministic text for a numeric DB field value."""
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, int):
        return str(v)
    f = float(v)
    if f == int(f) and abs(f) < 1e15:
        return str(int(f))
    return repr(f)


def qstr(s):
    s = str(s).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def fval(key, v):
    if isinstance(v, (int, float)) and not isinstance(v, bool):
        return qstr(fnum(v))
    return qstr(v)


class Rec:
    def __init__(self, name, rtyp):
        self.name = name
        self.rtyp = rtyp
        self.lines = []

    def field(self, k, v):
        self.lines.append(f'    field({k}, {fval(k, v)})')
        return self

    def render(self):
        body = "\n".join(self.lines)
        return f'record({self.rtyp}, "{self.name}") {{\n{body}\n}}\n'


# ---------------------------------------------------------------------------
# sampleGas.db
# ---------------------------------------------------------------------------

def _decimals(x):
    """Decimal places needed to show x exactly (up to 6): 41 -> 0, 0.05 -> 2, 8.8e-4 -> 5."""
    s = f"{abs(float(x)):.6f}".rstrip("0")
    return len(s.split(".")[1]) if "." in s else 0


def param_prec(p):
    """PREC of a Par:* ao: enough decimals for its default and both limits (so 41 L shows as
    41, not 41.0000), at most 6."""
    return min(6, max(_decimals(p["default"]), _decimals(p["min"]), _decimals(p["max"])))


def build_records():
    """Yield Rec objects in deterministic order: Par:*, Mode + Mode:<X>:*, then PVS in order."""
    # Par:<key>, one per PARAMS row (writeEnable is bo; everything else ao/longout).
    for p in T.PARAMS:
        name = f"$(P)Par:{p['key']}"
        if p["key"] == "writeEnable":
            r = Rec(name, "bo")
            r.field("DESC", desc_field(p["desc"]))
            r.field("ZNAM", "Shadow")
            r.field("ONAM", "Live")
            r.field("VAL", int(p["default"]))
            r.field("PINI", "YES")
            yield r
            continue
        rtyp = "longout" if p["integer"] else "ao"
        r = Rec(name, rtyp)
        r.field("DESC", desc_field(p["desc"]))
        if p["unit"] not in ("\u2013",):
            r.field("EGU", ascii_text(p["unit"]))
        if rtyp == "ao":
            r.field("PREC", str(param_prec(p)))
        r.field("DRVL", int(p["min"]) if p["integer"] else fnum(p["min"]))
        r.field("DRVH", int(p["max"]) if p["integer"] else fnum(p["max"]))
        r.field("VAL", int(p["default"]) if p["integer"] else fnum(p["default"]))
        r.field("PINI", "YES")
        # Note for the glue (Task 3): "target" is a normal ao record like any other Par:*, but a
        # put to it while REGULATE must be picked up through sg_set_target() (not a raw dbGet of
        # sg_params.target) so settling starts (spec §8.12). See sgPvTable.h for the same note.
        yield r

    # $(P)Mode and $(P)Mode:<X>:* (mode slots), spec §7.4.
    mode_pv = next(p for p in T.PVS if p["suffix"] == "Mode")
    r = Rec("$(P)Mode", mode_pv["rtyp"])
    if mode_pv.get("desc"):
        r.field("DESC", desc_field(mode_pv["desc"]))
    for k, v in mode_pv["fields"].items():
        r.field(k, v)
    r.field("PINI", "YES")
    yield r

    for slot in T.MODE_SLOTS:
        defaults = T.MODE_DEFAULTS[slot]
        r = Rec(f"$(P)Mode:{slot}:name", "stringout")
        r.field("VAL", defaults["name"])
        r.field("PINI", "YES")
        yield r
        for mf in T.MODE_FIELDS:
            field = mf["field"]
            r = Rec(f"$(P)Mode:{slot}:{field}", "ao")
            r.field("EGU", ascii_text(mf["unit"]) if mf["unit"] != "\u2013" else "")
            # enough decimals for every slot's default and the limits (as param_prec)
            r.field("PREC", str(min(6, max([_decimals(mf["min"]), _decimals(mf["max"])] +
                                           [_decimals(T.MODE_DEFAULTS[s][field])
                                            for s in T.MODE_SLOTS]))))
            r.field("DRVL", fnum(mf["min"]))
            r.field("DRVH", fnum(mf["max"]))
            r.field("VAL", fnum(defaults[field]))
            r.field("PINI", "YES")
            yield r

    # Everything else (PVS), in table order, skipping the Mode entry already emitted above.
    for pv in T.PVS:
        if pv["suffix"] == "Mode":
            continue
        name = f"$(P){pv['suffix']}"
        r = Rec(name, pv["rtyp"])
        if pv.get("desc"):
            r.field("DESC", desc_field(pv["desc"]))
        if pv["rtyp"] in ("lsi", "lso") and "SIZV" not in pv["fields"]:
            r.field("SIZV", 256)
        for k, v in pv["fields"].items():
            r.field(k, v)
        if pv.get("pini"):
            r.field("PINI", "YES")
        yield r


def build_db_text():
    parts = [HEADER, "\n"]
    for r in build_records():
        parts.append(r.render())
        parts.append("\n")
    return "".join(parts)


# ---------------------------------------------------------------------------
# autosave .req files
# ---------------------------------------------------------------------------

# Single source of truth (fix round 1, finding 4): the Par:* and Mode:<X>:* lines come straight
# from PARAMS / MODE_SLOTS / MODE_FIELDS (§10: "all Par:* (VAL)", "all Mode:* fields"); the rest
# of each .req file is generated by filtering PVS on its own 'autosave' tag, in PVS's own
# (deterministic) order, instead of a second hard-coded list that could silently drift from it.
# The one exception is "$(P)Mode"'s own state-string sub-fields (Mode.ZRST etc, per §10: "Mode
# (VAL) and the Mode mbbo state strings"): PVS has no notion of DB sub-fields, so those four
# lines are spliced in right after the PV they belong to.

def _autosaved_pvs(tag):
    return [pv for pv in T.PVS if pv["autosave"] == tag]


def build_settings_req_text():
    lines = [HEADER.rstrip("\n"), ""]
    for p in T.PARAMS:
        lines.append(f"$(P)Par:{p['key']}")
    for slot in T.MODE_SLOTS:
        lines.append(f"$(P)Mode:{slot}:name")
        for mf in T.MODE_FIELDS:
            lines.append(f"$(P)Mode:{slot}:{mf['field']}")
    for pv in _autosaved_pvs("settings"):
        lines.append(f"$(P){pv['suffix']}")
        if pv["suffix"] == "Mode":
            for fld in ["ZRST", "ONST", "TWST", "THST"]:
                lines.append(f"$(P)Mode.{fld}")
    return "\n".join(lines) + "\n"


def build_helium_req_text():
    lines = [HEADER.rstrip("\n"), ""]
    for pv in _autosaved_pvs("helium"):
        lines.append(f"$(P){pv['suffix']}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# sgPvTable.h / sgPvTable.c
# ---------------------------------------------------------------------------

def build_pvtable_h_text():
    return CHEADER + """#ifndef SGPVTABLE_H
#define SGPVTABLE_H
#include <stddef.h>

/* sgParPvs[i].suffix is the PV suffix INCLUDING the "Par:" prefix (e.g. "Par:target"). To form
   the full record name, the glue prepends only the station macro: "$(P)" + suffix, e.g.
   "$(P)" "Par:target" = "$(P)Par:target". offset is offsetof(sg_params, <field>) for the same
   field the key names (suffix "Par:target" -> field target). isInt is 1 for the five params
   whose EPICS record is longout (avgN, slopeAvgN, holdRetries, gainSchedule, lidMinSamples);
   the underlying sg_params field is still a double in every case.
   "target" is present here (offset is valid) but the glue must call sg_set_target(), not a raw
   store, so that a change while REGULATE starts settling (spec §8.12).
   "writeEnable" has NO entry: it is not a field of sg_params (it is IOC-glue state, spec §8.20). */
typedef struct { const char *suffix; size_t offset; int isInt; } sgParPv;
extern const sgParPv sgParPvs[];
extern const int sgNParPvs;

/* sgModePvs[i].suffix is BARE: just the mode-field name (e.g. "baseFlow"), with no "Mode:" and
   no slot letter. To form the full record name for slot X (one of 'A'..'D'), the glue builds
   "$(P)Mode:" + X + ":" + suffix, e.g. "$(P)Mode:B:baseFlow". offset is
   offsetof(sg_mode, <field>), to be added to a pointer to p->modes[0..3] (X - 'A'). The
   stringout "name" field is not here (it is a char[40], copied by the glue directly, not
   through this table). */
typedef struct { const char *suffix; size_t offset; } sgModePv;
extern const sgModePv sgModePvs[];
extern const int sgNModePvs;

#endif
"""


def build_pvtable_c_text():
    lines = [CHEADER, '#include "sgPvTable.h"', '#include "sgCore.h"', ""]
    lines.append("const sgParPv sgParPvs[] = {")
    for p in T.PARAMS:
        if p["key"] == "writeEnable":
            continue
        note = "  /* glue must call sg_set_target(), not a raw store (see sgPvTable.h) */" \
            if p["key"] == "target" else ""
        isint = 1 if p["integer"] else 0
        lines.append(
            f'    {{ "Par:{p["key"]}", offsetof(sg_params, {p["key"]}), {isint} }},{note}'
        )
    lines.append("};")
    lines.append("const int sgNParPvs = sizeof(sgParPvs) / sizeof(sgParPvs[0]);")
    lines.append("")
    lines.append("const sgModePv sgModePvs[] = {")
    for mf in T.MODE_FIELDS:
        field = mf["field"]
        lines.append(f'    {{ "{field}", offsetof(sg_mode, {field}) }},')
    lines.append("};")
    lines.append("const int sgNModePvs = sizeof(sgModePvs) / sizeof(sgModePvs[0]);")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# driver
# ---------------------------------------------------------------------------

OUTPUTS = {
    OUT_DB: build_db_text,
    OUT_SETTINGS_REQ: build_settings_req_text,
    OUT_HELIUM_REQ: build_helium_req_text,
    OUT_PVTABLE_H: build_pvtable_h_text,
    OUT_PVTABLE_C: build_pvtable_c_text,
}


def main(argv):
    check = "--check" in argv
    mismatches = []
    for path, builder in OUTPUTS.items():
        text = builder()
        if check:
            existing = None
            if os.path.exists(path):
                with open(path, "r", encoding="utf-8", newline="") as f:
                    existing = f.read()
            if existing != text:
                mismatches.append(path)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
    if check:
        if mismatches:
            for p in mismatches:
                print(f"gen_db.py --check: OUT OF DATE: {p}", file=sys.stderr)
            return 1
        print("gen_db.py --check: all generated files up to date")
        return 0
    print("gen_db.py: wrote", ", ".join(OUTPUTS))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
